// src/utils/exportReport.js

/**
 * Export the full evolution run as a JSON file.
 */
export function exportJSON(nodes, edges, logs, champion, problem) {
  const data = {
    meta: {
      tool: "phylo — Evolutionary Idea Market",
      exported_at: new Date().toISOString(),
      problem,
    },
    champion: champion || null,
    statistics: computeStats(nodes, edges),
    ideas: nodes.map(({ x, y, fx, fy, vx, vy, index, ...rest }) => rest),
    edges: edges.map((e) => ({
      source: typeof e.source === "object" ? e.source.id : e.source,
      target: typeof e.target === "object" ? e.target.id : e.target,
    })),
    logs,
  };
  download(JSON.stringify(data, null, 2), `phylo-run-${Date.now()}.json`, "application/json");
}

/**
 * Export a Markdown experiment report.
 */
export function exportMarkdown(nodes, edges, logs, champion, problem) {
  const s = computeStats(nodes, edges);
  const alive = nodes.filter((n) => n.status !== "dead").sort((a, b) => b.score - a.score);
  const topIdeas = alive.slice(0, 5);

  let md = `# Phylo — Experiment Report\n\n`;
  md += `> Generated by [phylo](https://github.com/) — Evolutionary Idea Market\n\n`;
  md += `**Date:** ${new Date().toLocaleString()}\n\n`;
  md += `## Seed Problem\n\n${problem}\n\n`;

  md += `## Summary Statistics\n\n`;
  md += `| Metric | Value |\n|---|---|\n`;
  md += `| Total Ideas Generated | ${s.total} |\n`;
  md += `| Survived | ${s.alive} (${s.survivalRate}%) |\n`;
  md += `| Eliminated | ${s.dead} |\n`;
  md += `| Generations | ${s.generations} |\n`;
  md += `| Avg Fitness Improvement | ${s.improvement}% |\n`;
  md += `| Best Score | ${s.bestScore} |\n`;
  md += `| Mutations | ${s.mutationCount} |\n`;
  md += `| Crossovers | ${s.crossoverCount} |\n\n`;

  if (champion) {
    md += `## 🏆 Champion\n\n`;
    md += `**Score:** ${champion.score.toFixed(3)}  \n`;
    md += `**Generation:** ${champion.generation}  \n`;
    md += `**Agent:** ${champion.agent_type}  \n\n`;
    md += `> ${champion.text}\n\n`;
  }

  md += `## Agent Performance\n\n`;
  md += `| Agent | Ideas | Avg Score | Best Score |\n|---|---|---|---|\n`;
  for (const a of s.agentStats) {
    md += `| ${a.type} | ${a.count} | ${a.avg} | ${a.best} |\n`;
  }
  md += `\n`;

  md += `## Top 5 Surviving Ideas\n\n`;
  topIdeas.forEach((idea, i) => {
    md += `### ${i + 1}. Score: ${idea.score.toFixed(3)} (G${idea.generation}, ${idea.agent_type})\n\n`;
    md += `${idea.text}\n\n`;
  });

  md += `## Evolution Log\n\n`;
  md += `\`\`\`\n`;
  md += logs.join("\n");
  md += `\n\`\`\`\n\n`;

  md += `---\n*Report generated by phylo — an evolutionary computation playground for AI-driven ideation.*\n`;

  download(md, `phylo-report-${Date.now()}.md`, "text/markdown");
}

function computeStats(nodes, edges) {
  const alive = nodes.filter((n) => n.status !== "dead");
  const dead = nodes.filter((n) => n.status === "dead");
  const allScores = nodes.map((n) => n.score);
  const generations = [...new Set(nodes.map((n) => n.generation))];

  const byAgent = {};
  for (const n of nodes) {
    if (!byAgent[n.agent_type]) byAgent[n.agent_type] = [];
    byAgent[n.agent_type].push(n.score);
  }
  const agentStats = Object.entries(byAgent).map(([type, scores]) => ({
    type,
    avg: (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(3),
    count: scores.length,
    best: Math.max(...scores).toFixed(3),
  }));

  const genAvgs = {};
  for (const n of nodes) {
    if (!genAvgs[n.generation]) genAvgs[n.generation] = [];
    genAvgs[n.generation].push(n.score);
  }
  const genAvgList = Object.entries(genAvgs)
    .sort(([a], [b]) => a - b)
    .map(([, s]) => s.reduce((a, b) => a + b, 0) / s.length);
  const improvement =
    genAvgList.length >= 2
      ? (((genAvgList[genAvgList.length - 1] - genAvgList[0]) / Math.max(genAvgList[0], 0.001)) * 100).toFixed(1)
      : "0";

  return {
    total: nodes.length,
    alive: alive.length,
    dead: dead.length,
    survivalRate: nodes.length > 0 ? ((alive.length / nodes.length) * 100).toFixed(1) : "0",
    bestScore: allScores.length > 0 ? Math.max(...allScores).toFixed(3) : "0",
    generations: generations.length,
    improvement,
    agentStats,
    mutationCount: nodes.filter((n) => n.agent_type === "mutator").length,
    crossoverCount: nodes.filter((n) => n.agent_type === "crossbreeder").length,
  };
}

function download(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
